### ISSUE TITLE
'BasicSolver' problem

### ISSUE THREAD

**Issue by alimatfi** [trincaog/magiccube#15]
(python 3.11 environment):
import magiccube
# 3x3x3 Cube
cube0 = magiccube.Cube(3,"YYYYYYYYYRRRRRRRRRGGGGGGGGGOOOOOOOOOBBBBBBBBBWWWWWWWWW")
print(cube0)
# Rotate the cube
cube0.rotate("R' L U D' F B' R' L")
# Solve the 3x3x3 cube
solver = BasicSolver(cube0)
solver.solve()

BUG is :
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[42], line 12
      9 cube0.rotate("R' L U D' F B' R' L")
     11 # Solve the 3x3x3 cube
---> 12 solver = BasicSolver(cube0)
     13 solver.solve()
     15 # 6x6x6 Cube

NameError: name 'BasicSolver' is not defined

**Comment by trincaog** [comment]
Thank you for reporting!
New release created. LMK if issues arise.
